<?php 
$title = 'Foosball';
$this->headTitle($title);
?>
<h2>Players</h2>
<p><a href="<?= $this->url('player', array( 
        'action'=>'add'));?>" title="Add Player">Add new player</a></p>

<table class="table">
<tr>
    <thead>
        <th>Name</th>
        <th>Email</th>
        <th>Points</th>
        <th>Edit</th>
    </thead>
    <tbody>
    <?php foreach ($players as $player):?>
        <tr>
            <td><?= $this->escapeHtml($player->firstname . ' ' . $player->lastname);?></td>
            <td><?= $this->escapeHtml($player->email);?></td>
            <td><?= $this->escapeHtml($player->points);?></td>
            <td><a href="<?= $this->url('player', array('action'=>'edit', 'id'=>$player->id));?>" title="Edit Player">Edit</a></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</tr>

</table>

<h2>Games</h2>
<p>coming..</p>