<?php 
$title = 'My Games';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><a href="<?php /*echo $this->url('album', array( 
        'action'=>'add'));*/?>">Add new album</a></p>

<table class="table">
<tr>
    <thead>
        <th>Name</th>
        <th>Email</th>
        <th>Points</th>
    </thead>
    <tbody>
    <?php foreach ($players as $player):?>
        <tr>
            <td><?= $this->escapeHtml($player->firstname . ' ' . $player->lastname);?></td>
            <td><?= $this->escapeHtml($player->email);?></td>
            <td><?= $this->escapeHtml($player->points);?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</tr>

</table>
